#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get -y upgrade
sudo apt install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt install -y haproxy
new_config="
frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend apache_webservers

backend apache_webservers
    balance roundrobin
    server 525779-web-01        34.229.66.172:80 check
    server 525779-web-02        54.82.132.21:80 check
"
config_file="/etc/haproxy/haproxy.cfg"
echo -e "$new_config" | sudo tee -a "$config_file" >> /dev/null
sudo service haproxy restart
sudo systemctl enable haproxy
